default:
  http_metas:
    content-type: text/html

  metas:
    title:        PowerDNS GUI
    robots:       index, follow
    description:  Web based GUI which aids in administering domains and records for the PowerDNS name server software with MySQL backend.
    keywords:     pdns, gui
    language:     en

  stylesheets:    [main]

  javascripts:    []

  has_layout:     on
  layout:         layout
